### ISSUE TITLE
submit button doesnt work - I press it and nothing happens

### ISSUE THREAD

**Issue by skywinder** [karlicoss/myinfra#1]
just want to say:
> Wow awesome project. Take my Kudos. I will try to use it. The similar project, that I really like is https://github.com/krausefx/fxlifesheet

<img width="906" alt="Screenshot 2020-03-21 at 12 46 25" src="https://user-images.githubusercontent.com/3356474/77220365-fc80d700-6b71-11ea-9305-d5964ed4adce.png">

**Comment by karlicoss** [comment]
@skywinder wow, thanks for letting me know! My commenting server has gone a bit mad apparently... Restored the comments from a backup and they should work now.

**Comment by karlicoss** [comment]
And thanks for the link too! That looks awesome, I'll check it out and add to the list.

**Comment by skywinder** [comment]
Thanks for your project
